llm:
  provider: "mock"
  model_id: "mock"

# Script-first test runner configuration

# Option 1: Use a shell script
# setup_script: "./scripts/setup_env.sh"
# test_script: "./scripts/run_tests.sh"
# single_test_script: "./scripts/run_one_test.sh"

# Option 2: Inline shell commands
setup_command: |
  pip install -e .

test_command: |
  pytest --tb=short -q

single_test_command: |
  pytest -q -k {test_name} --tb=short
