litellm:
  model: "claude-3-5-haiku-20241022"
  max_tokens: 8192
  debug_prompt: true
  mock_response: |
    Ring-ding-ding-ding-dingeringeding!
    Wa-pa-pa-pa-pa-pa-pow!
    Hatee-hatee-hatee-ho!
    Joff-tchoff-tchoffo-tchoffo-tchoff!”

setup_command: |
  pip install -e .

test_command: |
  pytest --tb=short -q

single_test_command: |
  pytest -q -k {test_name} --tb=short
