llm:
  provider: "ollama"
  model_id: "mistral"
  base_url: "http://localhost:11434"

setup_command: |
  echo "[Setup] Creating virtualenv..."
  python3 -m venv venv
  source venv/bin/activate
  pip install -e .

test_command: |
  echo "[Test] Running full suite..."
  source venv/bin/activate
  pytest --maxfail=5 --tb=short -q

single_test_command: |
  echo "[Test] Running single test: {test_name}"
  source venv/bin/activate
  pytest -q -k {test_name} --tb=short
